export const personMaleNames = [
  "Oliver",
  "George",
  "Arthur",
  "Noah",
  "Muhammad",
  "Leo",
  "Oscar",
  "Harry",
  "Archie",
  "Jack",
  "Henry",
  "Charlie",
  "Freddie",
  "Theodore",
  "Thomas",
  "Finley",
  "Theo",
  "Alfie",
  "Jacob",
  "William",
  "Isaac",
  "Tommy",
  "Joshua",
  "James",
  "Lucas",
  "Alexander",
  "Arlo",
  "Roman",
  "Edward",
  "Elijah",
  "Teddy",
  "Mohammed",
  "Max",
  "Adam",
  "Albie",
  "Ethan",
  "Logan",
  "Joseph",
  "Sebastian",
  "Benjamin",
  "Harrison",
  "Mason",
  "Rory",
  "Reuben",
  "Luca",
  "Louie",
  "Samuel",
  "Reggie",
  "Jaxon",
  "Daniel",
  "Hugo",
  "Louis",
  "Jude",
  "Ronnie",
  "Dylan",
  "Zachary",
  "Albert",
  "Hunter",
  "Ezra",
  "David",
  "Frankie",
  "Toby",
  "Frederick",
  "Carter",
  "Gabriel",
  "Grayson",
  "Riley",
  "Jesse",
  "Hudson",
  "Bobby",
  "Rowan",
  "Jenson",
  "Finn",
  "Michael",
  "Mohammad",
  "Stanley",
  "Felix",
  "Jasper",
  "Liam",
  "Milo",
  "Sonny",
  "Oakley",
  "Elliot",
  "Chester",
  "Caleb",
  "Harvey",
  "Elliott",
  "Charles",
  "Ellis",
  "Jackson",
  "Alfred",
  "Ollie",
  "Leon",
  "Yusuf",
  "Ralph",
  "Otis",
  "Harley",
  "Ibrahim",
  "Jayden",
  "Myles",
];

export const personFemaleNames = [
  "Olivia",
  "Amelia",
  "Isla",
  "Ava",
  "Mia",
  "Ivy",
  "Lily",
  "Isabella",
  "Rosie",
  "Sophia",
  "Grace",
  "Freya",
  "Willow",
  "Florence",
  "Emily",
  "Ella",
  "Poppy",
  "Evie",
  "Elsie",
  "Charlotte",
  "Evelyn",
  "Sienna",
  "Sofia",
  "Daisy",
  "Phoebe",
  "Sophie",
  "Alice",
  "Harper",
  "Matilda",
  "Ruby",
  "Emilia",
  "Maya",
  "Millie",
  "Isabelle",
  "Eva",
  "Luna",
  "Jessica",
  "Ada",
  "Aria",
  "Arabella",
  "Maisie",
  "Esme",
  "Eliza",
  "Penelope",
  "Bonnie",
  "Chloe",
  "Mila",
  "Violet",
  "Hallie",
  "Scarlett",
  "Layla",
  "Imogen",
  "Eleanor",
  "Molly",
  "Harriet",
  "Elizabeth",
  "Thea",
  "Erin",
  "Lottie",
  "Emma",
  "Rose",
  "Deliah",
  "Bella",
  "Aurora",
  "Lola",
  "Nancy",
  "Ellie",
  "Mabel",
  "Lucy",
  "Ayla",
  "Maria",
  "Orla",
  "Zara",
  "Robyn",
  "Hannah",
  "Gracie",
  "Iris",
  "Jasmine",
  "Darcie",
  "Margot",
  "Holly",
  "Amelie",
  "Amber",
  "Georgia",
  "Edith",
  "Maryam",
  "Abigail",
  "Myla",
  "Anna",
  "Clara",
  "Lilly",
  "Lyra",
  "Summer",
  "Maeve",
  "Heidi",
  "Elodie",
  "Lyla",
  "Eden",
  "Olive",
];

export const petNames = [
  "Abigail",
  "Ace",
  "Adam",
  "Addie",
  "Admiral",
  "Aggie",
  "Aires",
  "Aj",
  "Ajax",
  "Aldo",
  "Alex",
  "Alexus",
  "Alf",
  "Alfie",
  "Allie",
  "Ally",
  "Amber",
  "Amie",
  "Amigo",
  "Amos",
  "Amy",
  "Andy",
  "Angel",
  "Angus",
  "Annie",
  "Apollo",
  "April",
  "Archie",
  "Argus",
  "Aries",
  "Armanti",
  "Arnie",
  "Arrow",
  "Ashes",
  "Ashley",
  "Astro",
  "Athena",
  "Atlas",
  "Audi",
  "Augie",
  "Aussie",
  "Austin",
  "Autumn",
  "Axel",
  "Axle",
  "Babbles",
  "Babe",
  "Baby",
  "Baby-doll",
  "Babykins",
  "Bacchus",
  "Bailey",
  "Bam-bam",
  "Bambi",
  "Bandit",
  "Banjo",
  "Barbie",
  "Barclay",
  "Barker",
  "Barkley",
  "Barley",
  "Barnaby",
  "Barney",
  "Baron",
  "Bart",
  "Basil",
  "Baxter",
  "Bb",
  "Beamer",
  "Beanie",
  "Beans",
  "Bear",
  "Beau",
  "Beauty",
  "Beaux",
  "Bebe",
  "Beetle",
  "Bella",
  "Belle",
  "Ben",
  "Benji",
  "Benny",
  "Benson",
  "Bentley",
  "Bernie",
  "Bessie",
  "Biablo",
  "Bibbles",
  "Big Boy",
  "Big Foot",
  "Biggie",
  "Billie",
  "Billy",
  "Bingo",
  "Binky",
  "Birdie",
  "Birdy",
  "Biscuit",
  "Bishop",
  "Gus",
  "Guy",
  "Gypsy",
  "Hailey",
  "Haley",
  "Hallie",
  "Hamlet",
  "Hammer",
  "Hank",
  "Hanna",
  "Hannah",
  "Hans",
  "Happy",
  "Hardy",
  "Harley",
  "Harpo",
  "Harrison",
  "Harry",
  "Harvey",
  "Heather",
  "Heidi",
  "Henry",
  "Hercules",
  "Hershey",
  "Higgins",
  "Hobbes",
  "Holly",
  "Homer",
  "Honey",
  "Honey-Bear",
  "Hooch",
  "Hoover",
  "Hope",
  "Houdini",
  "Howie",
  "Hudson",
  "Huey",
  "Hugh",
  "Hugo",
  "Humphrey",
  "Hunter",
  "India",
  "Indy",
  "Iris",
  "Isabella",
  "Isabelle",
  "Itsy",
  "Itsy-bitsy",
  "Ivory",
  "Ivy",
  "Izzy",
  "Jack",
  "Jackie",
  "Jackpot",
  "Jackson",
  "Jade",
  "Jagger",
  "Jags",
  "Jaguar",
  "Jake",
  "Jamie",
  "Jasmine",
  "Jasper",
  "Jaxson",
  "Jazmie",
  "Jazz",
  "Jelly",
  "Jelly-bean",
  "Jenna",
  "Jenny",
  "Jerry",
  "Jersey",
  "Jess",
  "Jesse",
  "Jesse James",
  "Jessie",
  "Jester",
  "Jet",
  "Jethro",
  "Jett",
  "Jetta",
  "Jewel",
  "Jewels",
  "Jimmy",
  "Jingles",
  "JJ",
  "Joe",
  "Joey",
  "Johnny",
  "Jojo",
  "Joker",
  "Jolie",
  "Jolly",
  "Jordan",
  "Josie",
  "Joy",
  "JR",
  "Judy",
  "Julius",
  "June",
  "Misty",
  "Mitch",
  "Mittens",
  "Mitzi",
  "Mitzy",
  "Mo",
  "Mocha",
  "Mollie",
  "Molly",
  "Mona",
  "Muffy",
  "Nakita",
  "Nala",
  "Nana",
  "Natasha",
  "Nellie",
  "Nemo",
  "Nena",
  "Peanut",
  "Peanuts",
  "Pearl",
  "Pebbles",
  "Penny",
  "Phoebe",
  "Phoenix",
  "Sara",
  "Sarah",
  "Sasha",
  "Sassie",
  "Sassy",
  "Savannah",
  "Scarlett",
  "Shasta",
  "Sheba",
  "Sheena",
  "Shelby",
  "Shelly",
  "Sienna",
  "Sierra",
  "Silky",
  "Silver",
  "Simone",
  "Sissy",
  "Skeeter",
  "Sky",
  "Skye",
  "Skyler",
  "Waldo",
  "Wallace",
  "Wally",
  "Walter",
  "Wayne",
  "Weaver",
  "Webster",
  "Wesley",
  "Westie",
  "Abel",
  "Bits",
  "Bitsy",
  "Bizzy",
  "Bj",
  "Blackie",
  "Black-Jack",
  "Blast",
  "Blaze",
  "Blue",
  "Bo",
  "Bo",
  "Bob",
  "Bobbie",
  "Bobby",
  "Bobo",
  "Bodie",
  "Bogey",
  "Bones",
  "Bongo",
  "Boo",
  "Boo-boo",
  "Booker",
  "Boomer",
  "Boone",
  "Booster",
  "Bootie",
  "Boots",
  "Boozer",
  "Boris",
  "Bosco",
  "Bosley",
  "Boss",
  "Boy",
  "Bozley",
  "Bradley",
  "Brady",
  "Braggs",
  "Brando",
  "Bruiser",
  "Bruno",
  "Brutus",
  "Bubba",
  "Bubbles",
  "Buck",
  "Buckeye",
  "Bucko",
  "Bucky",
  "Bud",
  "Budda",
  "Buddie",
  "Buddy",
  "Buddy Boy",
  "Kane",
  "Karma",
  "Kato",
  "Katz",
  "Kibbles",
  "Kid",
  "Killian",
  "King",
  "Kipper",
  "Kirby",
  "Kismet",
  "Klaus",
  "Koba",
  "Kobe",
  "Koda",
  "Koko",
  "Kona",
  "Kosmo",
  "Koty",
  "Kramer",
  "Kujo",
  "Kurly",
  "Lassie",
  "Latte",
  "Lincoln",
  "Linus",
  "Little Bit",
  "Little-guy",
  "Little-one",
  "Little-rascal",
  "Lucifer",
  "Lucky",
  "Maverick",
  "Max",
  "Maximus",
  "Mercle",
  "Merlin",
  "Pooch",
  "Poochie",
  "Rover",
  "Scoobie",
  "Scooby",
  "Scooby-doo",
  "Slick",
  "Slinky",
  "Sly",
  "Snoopy",
  "Smarty",
  "Sox",
  "Spanky",
  "Spud",
  "Spunky",
  "Squeeky",
  "Squirt",
  "Stanley",
  "Sterling",
  "Stich",
  "Stink",
  "Ty",
  "Tyler",
  "Tyson",
  "Vinnie",
  "Vinny",
  "Willie",
  "Wizard",
  "Wolfgang",
  "Wolfie",
  "Woody",
  "Woofie",
  "Wrigley",
  "Wrinkles",
  "Wyatt",
  "Yin",
  "Yoda",
  "Yogi",
  "Yogi-bear",
  "Yukon",
  "Zack",
  "Zeke",
  "Zeus",
  "Abbey",
  "Abbie",
  "Abby",
  "Blanche",
  "Blondie",
  "Blossom",
  "Bonnie",
  "Brandi",
  "Brandy",
  "Bridgett",
  "Bridgette",
  "Brie",
  "Brindle",
  "Brit",
  "Brittany",
  "Brodie",
  "Brook",
  "Brooke",
  "Brownie",
  "Buffie",
  "Buffy",
  "Bug",
  "Bugsey",
  "Bugsy",
  "Butter",
  "Butterball",
  "Buttercup",
  "Butterscotch",
  "Buttons",
  "Buzzy",
  "Cali",
  "Callie",
  "Cameo",
  "Camille",
  "Candy",
  "Carley",
  "Casey",
  "Casper",
  "Cassie",
  "Cassis",
  "Cha Cha",
  "Chanel",
  "Chaos",
  "Charisma",
  "Chelsea",
  "Cherokee",
  "Chessie",
  "Cheyenne",
  "Chi Chi",
  "Chic",
  "Chiquita",
  "Chivas",
  "Chloe",
  "Chocolate",
  "Chrissy",
  "Cinnamon",
  "Cisco",
  "Claire",
  "Coconut",
  "Codi",
  "Cody",
  "Kali",
  "Kallie",
  "Kasey",
  "Katie",
  "Kayla",
  "KC",
  "Keesha",
  "Kellie",
  "Kelly",
  "Kelsey",
  "Kenya",
  "Kerry",
  "Kiki",
  "Kira",
  "Kissy",
  "Kitty",
  "Kiwi",
  "Kyra",
  "Lacey",
  "Lady",
  "Ladybug",
  "Laney",
  "Layla",
  "Lexi",
  "Lexie",
  "Lexus",
  "Libby",
  "Lightning",
  "Nikita",
  "Nikki",
  "Niko",
  "Nina",
  "Olive",
  "Olivia",
  "Ollie",
  "Onie",
  "Pandora",
  "Patsy",
  "Patty",
  "Peaches",
  "Tequila",
  "Tess",
  "Tessa",
  "Tessie",
  "Valinto",
  "Vava",
  "Vegas",
  "Velvet",
  "Bullet",
  "Bullwinkle",
  "Bully",
  "Bumper",
  "Bunky",
  "Buster",
  "Buster-brown",
  "Butch",
  "Butchy",
  "Caesar",
  "Calvin",
  "Capone",
  "Captain",
  "Chad",
  "Chamberlain",
  "Champ",
  "Chance",
  "Charles",
  "Charlie",
  "Charlie Brown",
  "Charmer",
  "Chase",
  "Chauncey",
  "Chaz",
  "Checkers",
  "Chester",
  "Chevy",
  "Chewie",
  "Chewy",
  "Chico",
  "Chief",
  "Chili",
  "China",
  "Chip",
  "Chipper",
  "Chippy",
  "Chips",
  "Chubbs",
  "Chucky",
  "Chyna",
  "Cinder",
  "Cindy",
  "Clancy",
  "Cleo",
  "Cleopatra",
  "Clicker",
  "Clifford",
  "Clover",
  "Clyde",
  "Coal",
  "Cobweb",
  "Coco",
  "Cocoa",
  "Cole",
  "Comet",
  "Commando",
  "Conan",
  "Connor",
  "Cookie",
  "Cooper",
  "Copper",
  "Corky",
  "Cosmo",
  "Cotton",
  "Cozmo",
  "Crackers",
  "Cricket",
  "Crystal",
  "Cubby",
  "Cubs",
  "Cujo",
  "Cupcake",
  "Curly",
  "Curry",
  "Cutie",
  "Cutie-pie",
  "Cyrus",
  "Daffy",
  "Daisey-mae",
  "Daisy",
  "Dakota",
  "Dallas",
  "Dandy",
  "Dante",
  "Daphne",
  "Darby",
  "Darcy",
  "Darwin",
  "Dash",
  "Dave",
  "Deacon",
  "Dee",
  "Dee Dee",
  "Dempsey",
  "Destini",
  "Dewey",
  "Dexter",
  "Dharma",
  "Diamond",
  "Dickens",
  "Diego",
  "Diesel",
  "Digger",
  "Dillon",
  "Dinky",
  "Dino",
  "Diva",
  "Dixie",
  "Dobie",
  "Doc",
  "Dodger",
  "Doggon’",
  "Dolly",
  "Domino",
  "Doodles",
  "Doogie",
  "Dots",
  "Dottie",
  "Dozer",
  "Dragster",
  "Dreamer",
  "Duchess",
  "Dude",
  "Dudley",
  "Duffy",
  "Duke",
  "Duncan",
  "Dunn",
  "Dusty",
  "Dutches",
  "Dutchess",
  "Dylan",
  "Earl",
  "Ebony",
  "Echo",
  "Eddie",
  "Eddy",
  "Edgar",
  "Edsel",
  "Eifel",
  "Einstein",
  "Ellie",
  "Elliot",
  "Elmo",
  "Elvis",
  "Elwood",
  "Ember",
  "Emily",
  "Emma",
  "Emmy",
  "Erin",
  "Ernie",
  "Eva",
  "Faith",
  "Fancy",
  "Felix",
  "Fergie",
  "Ferris",
  "Fido",
  "Fifi",
  "Figaro",
  "Finnegan",
  "Fiona",
  "Flake",
  "Flakey",
  "Flash",
  "Flint",
  "Flopsy",
  "Flower",
  "Floyd",
  "Fluffy",
  "Fonzie",
  "Foxy",
  "Francais",
  "Frankie",
  "Franky",
  "Freckles",
  "Fred",
  "Freddie",
  "Freddy",
  "Freedom",
  "Freeway",
  "Fresier",
  "Friday",
  "Frisco",
  "Frisky",
  "Fritz",
  "Frodo",
  "Frosty",
  "Furball",
  "Fuzzy",
  "Gabby",
  "Gabriella",
  "Garfield",
  "Gasby",
  "Gator",
  "Gavin",
  "Genie",
  "George",
  "Georgia",
  "Georgie",
  "Giant",
  "Gibson",
  "Gidget",
  "Gigi",
  "Gilbert",
  "Gilda",
  "Ginger",
  "Ginny",
  "Girl",
  "Gizmo",
  "Godiva",
  "Goldie",
  "Goober",
  "Goose",
  "Gordon",
  "Grace",
  "Grace",
  "Gracie",
  "Gracie",
  "Grady",
  "Greenie",
  "Greta",
  "Gretchen",
  "Gretel",
  "Gretta",
  "Griffen",
  "Gringo",
  "Grizzly",
  "Gromit",
  "Grover",
  "Gucci",
  "Guido",
  "Guinness",
  "Gunner",
  "Gunther",
  "Laddie",
  "Lazarus",
  "Lefty",
  "Leo",
  "Levi",
  "Logan",
  "Loki",
  "Lou",
  "Louie",
  "Louis",
  "Lucas",
  "Mac",
  "Macho",
  "Macintosh",
  "Mack",
  "Magic",
  "Major",
  "Mason",
  "Maxwell",
  "Mcduff",
  "Michael",
  "Mickey",
  "Midnight",
  "Mikey",
  "Miko",
  "Miles",
  "Miller",
  "Milo",
  "Mister",
  "Mojo",
  "Monkey",
  "Monster",
  "Montana",
  "Montgomery",
  "Monty",
  "Moocher",
  "Moochie",
  "Mookie",
  "Moonshine",
  "Moose",
  "Morgan",
  "Moses",
  "Mouse",
  "Mr Kitty",
  "Muffin",
  "Mugsy",
  "Mulligan",
  "Munchkin",
  "Murphy",
  "Napoleon",
  "Nathan",
  "Nero",
  "Nestle",
  "Newt",
  "Newton",
  "Nibbles",
  "Nibby",
  "Nibby-nose",
  "Nick",
  "Nickers",
  "Nickie",
  "Nicky",
  "Nico",
  "Nike",
  "Niki",
  "Nitro",
  "Nobel",
  "Noel",
  "Nona",
  "Noodles",
  "Norton",
  "Nosey",
  "Nugget",
  "Nutmeg",
  "Oakley",
  "Obie",
  "Odie",
  "Old Glory",
  "Oliver",
  "Onyx",
  "Opie",
  "Oreo",
  "Oscar",
  "Otis",
  "Otto",
  "Oz",
  "Ozzie",
  "Ozzy",
  "Pablo",
  "Paco",
  "Paddington",
  "Paddy",
  "Panda",
  "Panther",
  "Papa",
  "Paris",
  "Parker",
  "Pasha",
  "Patch",
  "Patches",
  "Patricky",
  "Pedro",
  "Pepe",
  "Pepper",
  "Peppy",
  "Pepsi",
  "Persy",
  "Pete",
  "Peter",
  "Petey",
  "Petie",
  "Phantom",
  "Picasso",
  "Pickles",
  "Pierre",
  "Piggy",
  "Piglet",
  "Pink Panther",
  "Pinky",
  "Pinto",
  "Plato",
  "Pluto",
  "Pockets",
  "Pogo",
  "Pokey",
  "Pip-squeek",
  "Pirate",
  "Poncho",
  "Pongo",
  "Pooh",
  "Pooh-bear",
  "Porkchop",
  "Porky",
  "Porter",
  "Powder",
  "Prancer",
  "Prince",
  "Puck",
  "Puddles",
  "Pudge",
  "Puffy",
  "Pugsley",
  "Pumpkin",
  "Punkin",
  "Puppy",
  "Purdy",
  "Quinn",
  "Rags",
  "Raison",
  "Ralph",
  "Ralphie",
  "Rambler",
  "Rambo",
  "Ranger",
  "Rascal",
  "Rebel",
  "Red",
  "Reggie",
  "Reilly",
  "Remy",
  "Rex",
  "Rexy",
  "Rhett",
  "Ricky",
  "Rico",
  "Riggs",
  "Riley",
  "Rin Tin Tin",
  "Ringo",
  "Ripley",
  "Rocco",
  "Rock",
  "Rocket",
  "Rocko",
  "Rocky",
  "Roland",
  "Rolex",
  "Rollie",
  "Roman",
  "Romeo",
  "Roscoe",
  "Rosebud",
  "Rudy",
  "Ruffe",
  "Ruffer",
  "Ruffles",
  "Rufus",
  "Ruger",
  "Rusty",
  "Sage",
  "Sailor",
  "Salem",
  "Sampson",
  "Samson",
  "Sarge",
  "Sawyer",
  "Schotzie",
  "Schultz",
  "Scooter",
  "Scottie",
  "Scout",
  "Scrappy",
  "Scruffy",
  "Shadow",
  "Shady",
  "Shaggy",
  "Sherman",
  "Shiloh",
  "Shiner",
  "Shorty",
  "Sebastian",
  "Silvester",
  "Simba",
  "Simon",
  "Skinny",
  "Skip",
  "Skipper",
  "Skippy",
  "Skittles",
  "Mandi",
  "Mandy",
  "Mango",
  "Marble",
  "Mariah",
  "Marley",
  "Mary",
  "Mary Jane",
  "Mattie",
  "Maxine",
  "May",
  "Maya",
  "Mckenzie",
  "Meadow",
  "Megan",
  "Meggie",
  "Mercedes",
  "Mia",
  "Miasy",
  "Millie",
  "Mimi",
  "Mindy",
  "Ming",
  "Mini",
  "Minnie",
  "Mischief",
  "Misha",
  "Miss Kitty",
  "Miss Priss",
  "Missie",
  "Missy",
  "Piper",
  "Pippin",
  "Pippy",
  "Pixie",
  "Polly",
  "Pookie",
  "Pooky",
  "Popcorn",
  "Poppy",
  "Porch",
  "Precious",
  "Presley",
  "Pretty",
  "Pretty-girl",
  "Princess",
  "Prissy",
  "Queen",
  "Queenie",
  "Quincy",
  "Raven",
  "Rosa",
  "Rosie",
  "Rosy",
  "Rowdy",
  "Roxanne",
  "Roxie",
  "Roxy",
  "Ruby",
  "Ruchus",
  "Ruthie",
  "Ryder",
  "Sabine",
  "Sable",
  "Sabrina",
  "Sadie",
  "Sally",
  "Salty",
  "Sam",
  "Samantha",
  "Sammy",
  "Sandy",
  "Smoke",
  "Smokey",
  "Smudge",
  "Sneakers",
  "Snickers",
  "Snoop",
  "Snowball",
  "Snowflake",
  "Snowy",
  "Snuffles",
  "Snuggles",
  "Solomon",
  "Sonny",
  "Sophia",
  "Sophie",
  "Sparkle",
  "Sparky",
  "Speed",
  "Speedo",
  "Speedy",
  "Spirit",
  "Spookey",
  "Spot",
  "Spotty",
  "Star",
  "Starr",
  "Stella",
  "Stormy",
  "Sugar",
  "Sugar-baby",
  "Summer",
  "Sumo",
  "Sundance",
  "Sunday",
  "Sunny",
  "Sunshine",
  "Susie",
  "Susie-q",
  "Suzy",
  "Sweetie",
  "Sweetie-pie",
  "Sweet-pea",
  "Sydney",
  "Tabby",
  "Tabetha",
  "Taco",
  "Taffy",
  "Tally",
  "Tammy",
  "Tangles",
  "Tango",
  "Tank",
  "Tara",
  "Tasha",
  "Taylor",
  "Thelma",
  "Thyme",
  "Tiffany",
  "Tiger",
  "Tigger",
  "Tiggy",
  "Tiki",
  "Tilly",
  "Timber",
  "Tippy",
  "Titan",
  "Tito",
  "Titus",
  "Tobie",
  "Toby",
  "Toffee",
  "Toni",
  "Tony",
  "Toots",
  "Tootsie",
  "Topaz",
  "Tori",
  "Toto",
  "Tracker",
  "Tramp",
  "Trapper",
  "Trinity",
  "Tripod",
  "Tristan",
  "Trixie",
  "Trooper",
  "Trouble",
  "Zena",
  "Ziggy",
  "Zippy",
  "Zoe",
  "Zoey",
  "Zoie",
  "Spencer",
  "Spike",
  "Stuart",
  "Tank",
  "Tanner",
  "Taz",
  "T-bird",
  "T-bone",
  "Teddy",
  "Teddy-bear",
  "Tex",
  "Thor",
  "Thumper",
  "Thunder",
  "Timmy",
  "Tinker",
  "Tinker-bell",
  "Tinky",
  "Tiny",
  "Tipper",
  "Tom",
  "Tommy",
  "Tommy-boy",
  "Travis",
  "Trigger",
  "Troy",
  "Truffles",
  "Tuck",
  "Tucker",
  "Tuesday",
  "Tuffy",
  "Turbo",
  "Turner",
  "Tux",
  "Twiggy",
  "Twinkle",
  "Violet",
  "Vito",
  "Volvo",
  "Waddles",
  "Wags",
  "Whiskers",
  "Whiskey",
  "Whispy",
  "Whitie",
  "Whiz",
  "Wiggles",
  "Wilber",
  "Willow",
  "Willy",
  "Wilson",
  "Winnie",
  "Winston",
  "Winter",
  "Wiz",
  "Xena",
  "Yaka",
  "Yang",
  "Yeller",
  "Yellow",
  "Zorro",
];

export const jobTitles = [
  "Marketing Specialist",
  "Marketing Manager",
  "Marketing Director",
  "Graphic Designer",
  "Marketing Research Analyst",
  "Marketing Communications Manager",
  "Marketing Consultant",
  "Product Manager",
  "Public Relations",
  "Social Media Assistant",
  "Brand Manager",
  "SEO Manager",
  "Content Marketing Manager",
  "Copywriter",
  "Media Buyer",
  "Digital Marketing Manager",
  "eCommerce Marketing Specialist",
  "Brand Strategist",
  "Vice President of Marketing",
  "Media Relations Coordinator",
  "Administrative Assistant",
  "Receptionist",
  "Office Manager",
  "Auditing Clerk",
  "Bookkeeper",
  "Account Executive",
  "Branch Manager",
  "Business Manager",
  "Quality Control Coordinator",
  "Administrative Manager",
  "Chief Executive Officer",
  "Business Analyst",
  "Risk Manager",
  "Human Resources",
  "Office Assistant",
  "Secretary",
  "Office Clerk",
  "File Clerk",
  "Account Collector",
  "Administrative Specialist",
  "Executive Assistant",
  "Program Administrator",
  "Program Manager",
  "Administrative Analyst",
  "Data Entry",
  "Team Leader",
  "Manager",
  "Assistant Manager",
  "Executive",
  "Director",
  "Coordinator",
  "Administrator",
  "Controller",
  "Officer",
  "Organizer",
  "Supervisor",
  "Superintendent",
  "Head",
  "Overseer",
  "Chief",
  "Foreman",
  "Controller",
  "Principal",
  "President",
  "Lead",
  "Computer Scientist",
  "IT Professional",
  "UX Designer & UI Developer",
  "SQL Developer",
  "Web Designer",
  "Web Developer",
  "Help Desk Worker/Desktop Support",
  "Software Engineer",
  "Data Entry",
  "DevOps Engineer",
  "Computer Programmer",
  "Network Administrator",
  "Information Security Analyst",
  "Artificial Intelligence Engineer",
  "Cloud Architect",
  "IT Manager",
  "Technical Specialist",
  "Application Developer",
  "Chief Technology Officer (CTO)",
  "Chief Information Officer (CIO)",
  "Sales Associate",
  "Sales Representative",
  "Sales Manager",
  "Retail Worker",
  "Store Manager",
  "Sales Representative",
  "Sales Manager",
  "Real Estate Broker",
  "Sales Associate",
  "Cashier",
  "Store Manager",
  "Account Executive",
  "Account Manager",
  "Area Sales Manager",
  "Direct Salesperson",
  "Director of Inside Sales",
  "Outside Sales Manager",
  "Sales Analyst",
  "Market Development Manager",
  "B2B Sales Specialist",
  "Sales Engineer",
  "Merchandising Associate",
  "Construction Worker",
  "Taper",
  "Plumber",
  "Heavy Equipment Operator",
  "Vehicle or Equipment Cleaner",
  "Carpenter",
  "Electrician",
  "Painter",
  "Welder",
  "Handyman",
  "Boilermaker",
  "Crane Operator",
  "Building Inspector",
  "Pipefitter",
  "Sheet Metal Worker",
  "Iron Worker",
  "Mason",
  "Roofer",
  "Solar Photovoltaic Installer",
  "Well Driller",
  "CEO",
  "Proprietor",
  "Principal",
  "Owner",
  "President",
  "Founder",
  "Administrator",
  "Director",
  "Managing Partner",
  "Managing Member",
  "Board of Directors",
  "C-Level or C-Suite.",
  "Shareholders",
  "Managers",
  "Supervisors",
  "Front-Line Employees",
  "Quality Control",
  "Human Resources",
  "Accounting Staff",
  "Marketing Staff",
  "Purchasing Staff",
  "Shipping and Receiving Staff",
  "Office Manager",
  "Receptionist",
  "Virtual Assistant",
  "Customer Service",
  "Customer Support",
  "Concierge",
  "Help Desk",
  "Customer Service Manager",
  "Technical Support Specialist",
  "Account Representative",
  "Client Service Specialist",
  "Customer Care Associate",
  "Operations Manager",
  "Operations Assistant",
  "Operations Coordinator",
  "Operations Analyst",
  "Operations Director",
  "Vice President of Operations",
  "Operations Professional",
  "Scrum Master",
  "Continuous Improvement Lead",
  "Continuous Improvement Consultant",
  "Credit Authorizer",
  "Benefits Manager",
  "Credit Counselor",
  "Accountant",
  "Bookkeeper",
  "Accounting Analyst",
  "Accounting Director",
  "Accounts Payable/Receivable Clerk",
  "Auditor",
  "Budget Analyst",
  "Controller",
  "Financial Analyst",
  "Finance Manager",
  "Economist",
  "Payroll Manager",
  "Payroll Clerk",
  "Financial Planner",
  "Financial Services Representative",
  "Finance Director",
  "Commercial Loan Officer",
  "Engineer",
  "Mechanical Engineer",
  "Civil Engineer",
  "Electrical Engineer",
  "Assistant Engineer",
  "Chemical Engineer",
  "Chief Engineer",
  "Drafter",
  "Engineering Technician",
  "Geological Engineer",
  "Biological Engineer",
  "Maintenance Engineer",
  "Mining Engineer",
  "Nuclear Engineer",
  "Petroleum Engineer",
  "Plant Engineer",
  "Production Engineer",
  "Quality Engineer",
  "Safety Engineer",
  "Sales Engineer",
  "Chief People Officer",
  "VP of Miscellaneous Stuff",
  "Chief Robot Whisperer",
  "Director of First Impressions",
  "Culture Operations Manager",
  "Director of Ethical Hacking",
  "Software Ninjaneer",
  "Director of Bean Counting",
  "Digital Overlord",
  "Director of Storytelling",
  "Researcher",
  "Research Assistant",
  "Data Analyst",
  "Business Analyst",
  "Financial Analyst",
  "Biostatistician",
  "Title Researcher",
  "Market Researcher",
  "Title Analyst",
  "Medical Researcher",
  "Mentor",
  "Tutor/Online Tutor",
  "Teacher",
  "Teaching Assistant",
  "Substitute Teacher",
  "Preschool Teacher",
  "Test Scorer",
  "Online ESL Instructor",
  "Professor",
  "Assistant Professor",
  "Graphic Designer",
  "Artist",
  "Interior Designer",
  "Video Editor",
  "Video or Film Producer",
  "Playwright",
  "Musician",
  "Novelist/Writer",
  "Computer Animator",
  "Photographer",
  "Camera Operator",
  "Sound Engineer",
  "Motion Picture Director",
  "Actor",
  "Music Producer",
  "Director of Photography",
  "Nurse",
  "Travel Nurse",
  "Nurse Practitioner",
  "Doctor",
  "Caregiver",
  "CNA",
  "Physical Therapist",
  "Pharmacist",
  "Pharmacy Assistant",
  "Medical Administrator",
  "Medical Laboratory Tech",
  "Physical Therapy Assistant",
  "Massage Therapy",
  "Dental Hygienist",
  "Orderly",
  "Personal Trainer",
  "Massage Therapy",
  "Medical Laboratory Tech",
  "Phlebotomist",
  "Medical Transcriptionist",
  "Telework Nurse/Doctor",
  "Reiki Practitioner",
  "Housekeeper",
  "Flight Attendant",
  "Travel Agent",
  "Hotel Front Door Greeter",
  "Bellhop",
  "Cruise Director",
  "Entertainment Specialist",
  "Hotel Manager",
  "Front Desk Associate",
  "Front Desk Manager",
  "Concierge",
  "Group Sales",
  "Event Planner",
  "Porter",
  "Spa Manager",
  "Wedding Coordinator",
  "Cruise Ship Attendant",
  "Casino Host",
  "Hotel Receptionist",
  "Reservationist",
  "Events Manager",
  "Meeting Planner",
  "Lodging Manager",
  "Director of Maintenance",
  "Valet",
  "Waiter/Waitress",
  "Server",
  "Chef",
  "Fast Food Worker",
  "Barista",
  "Line Cook",
  "Cafeteria Worker",
  "Restaurant Manager",
  "Wait Staff Manager",
  "Bus Person",
  "Restaurant Chain Executive",
  "Political Scientist",
  "Chemist",
  "Conservation Scientist",
  "Sociologist",
  "Biologist",
  "Geologist",
  "Physicist",
  "Astronomer",
  "Atmospheric Scientist",
  "Molecular Scientist",
  "Call Center Representative",
  "Customer Service",
  "Telemarketer",
  "Telephone Operator",
  "Phone Survey Conductor",
  "Dispatcher for Trucks or Taxis",
  "Customer Support Representative",
  "Over the Phone Interpreter",
  "Phone Sales Specialist",
  "Mortgage Loan Processor",
  "Counselor",
  "Mental Health Counselor",
  "Addiction Counselor",
  "School Counselor",
  "Speech Pathologist",
  "Guidance Counselor",
  "Social Worker",
  "Therapist",
  "Life Coach",
  "Couples Counselor",
  "Beautician",
  "Hair Stylist",
  "Nail Technician",
  "Cosmetologist",
  "Salon Manager",
  "Makeup Artist",
  "Esthetician",
  "Skin Care Specialist",
  "Manicurist",
  "Barber",
  "Journalist",
  "Copy Editor",
  "Editor/Proofreader",
  "Content Creator",
  "Speechwriter",
  "Communications Director",
  "Screenwriter",
  "Technical Writer",
  "Columnist",
  "Public Relations Specialist",
  "Proposal Writer",
  "Content Strategist",
  "Grant Writer",
  "Video Game Writer",
  "Translator",
  "Film Critic",
  "Copywriter",
  "Travel Writer",
  "Social Media Specialist",
  "Ghostwriter",
  "Warehouse Worker",
  "Painter",
  "Truck Driver",
  "Heavy Equipment Operator",
  "Welding",
  "Physical Therapy Assistant",
  "Housekeeper",
  "Landscaping Worker",
  "Landscaping Assistant",
  "Mover",
  "Animal Breeder",
  "Veterinary Assistant",
  "Farm Worker",
  "Animal Shelter Worker",
  "Dog Walker / Pet Sitter",
  "Zoologist",
  "Animal Trainer",
  "Service Dog Trainer",
  "Animal Shelter Manager",
  "Animal Control Officer",
  "Delivery Driver",
  "School Bus Driver",
  "Truck Driver",
  "Tow Truck Operator",
  "UPS Driver",
  "Mail Carrier",
  "Recyclables Collector",
  "Courier",
  "Bus Driver",
  "Cab Driver",
  "Animal Shelter Board Member",
  "Office Volunteer",
  "Animal Shelter Volunteer",
  "Hospital Volunteer",
  "Youth Volunteer",
  "Food Kitchen Worker",
  "Homeless Shelter Worker",
  "Conservation Volunteer",
  "Meals on Wheels Driver",
  "Habitat for Humanity Builder",
  "Emergency Relief Worker",
  "Red Cross Volunteer",
  "Community Food Project Worker",
  "Women’s Shelter Jobs",
  "Suicide Hotline Volunteer",
  "School Volunteer",
  "Community Volunteer Jobs",
  "Sports Volunteer",
  "Church Volunteer",
  "Archivist",
  "Actuary",
  "Architect",
  "Personal Assistant",
  "Entrepreneur",
  "Security Guard",
  "Mechanic",
  "Recruiter",
  "Mathematician",
  "Locksmith",
  "Management Consultant",
  "Shelf Stocker",
  "Caretaker or House Sitter",
  "Library Assistant",
  "Translator",
  "HVAC Technician",
  "Attorney",
  "Paralegal",
  "Executive Assistant",
  "Personal Assistant",
  "Bank Teller",
  "Parking Attendant",
  "Machinery Operator",
  "Manufacturing Assembler",
  "Funeral Attendant",
  "Assistant Golf Professional",
  "Yoga Instructor",
  "",
];

export const countryNames = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Rep",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo {Democratic Rep}",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland {Republic}",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea North",
  "Korea South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar, {Burma}",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "St Kitts & Nevis",
  "St Lucia",
  "Saint Vincent & the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome & Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad & Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const vowels = ["a", "e", "i", "o", "u"];

export const consonants = [
  "b",
  "c",
  "d",
  "f",
  "g",
  "h",
  "j",
  "k",
  "l",
  "m",
  "n",
  "p",
  "q",
  "r",
  "s",
  "t",
  "v",
  "w",
  "x",
  "y",
  "z",
  "",
];

// To be added in future versions
// const carNames = [];
// const countryNames = [];
// const colorNames = [];
// const foodNames = [];
// const deviceNames = [];
// const randomPhrases = [];
// const skillNames = [];
// const courseNames = [];
// const interestNames = [];
// const symptomNames = [];
// const medicineNames = [];
// const bodyPartNames = [];
// const planetNames = [];
// const brandNames = [];
// const clothNames = [];
// const drinkNames = [];
// const gameTitles = [];
// const movieTitles = [];
// const songNames = [];
// const sportNames = [];
// const stateNames = [];
// const cityNames = [];
